name: core
description: A new Flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # State Management
  provider: ^6.0.3

  # Local Operations
  flutter_secure_storage: ^6.0.0

 # Network
  dio: ^4.0.6

  # Format
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.core
    iosBundleIdentifier: com.example.core
